[package]
name = "engula"
version = "0.3.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://engula.io"
repository = "https://github.com/engula/engula"
keywords = ["cache", "database"]
categories = ["caching", "database", "data-structures"]
description = "A low-latency, high-performance data structure store."

[dependencies]
engula-server = { version = "0.3", path = "../server" }

clap = { version = "3.0", features = ["derive"] }
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.2"
